environment   = "development"
region        = "eu-west-3"
ami_id        = "ami-087855b6c8b59a9e4"
instance_type = "t2.micro"
pem_key       = "paris-key"
stop_time     = "00 15 * * MON-FRI"
start_time    = "00 10 * * MON-FRI"